permalink: pretty
markdown: kramdown
baseurl: "/rails-girls-guides"
keep_files:
  - "css"
  - "js"
  - "images"
  - "favicon.png"
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".ruby-version"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
